### PR TITLE
Update: Plansum to Python 3

### PR DESCRIPTION
**Pull request by StephenTerry**
Updating the Plansum plugin.  Should we update the rest or wait for the authors to do it?

### CODE REVIEW

**Comment by bastula** [comment]
I haven't tested this, but does this work with all the changes that were applied to @dicompyler/core dicompyler (master)?

**Comment by StephenTerry** [comment]
Apparently my dicompyler-core was still set to my fork, so I was not
updated to your latest commits.  I'm fixing that, and I'll do some more
testing.

**Comment by StephenTerry** [comment]
The plugin works with my test data after updating to the latest core commit.

**Comment by bastula** [comment]
Sorry too many repos... 😄

**Pull request merged**
